// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

export const RESET_FILTER = 'RESET_FILTER'
export const ADD_FILTER = 'ADD_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'
export const SET_SELECTED_COMPANIES = 'SET_SELECTED_COMPANIES'
export const FETCH_SEARCH = 'FETCH_SEARCH'
export const LOADING_SEARCH = 'LOADING_SEARCH'
